### ISSUE TITLE
What are some of your favorite podcasts for programmers? 

### ISSUE THREAD

**Issue by lucidsif** [swyxio/ama#3]
Why those?

**Comment by swyxio** [comment]
haha, I listen to a looot of podcasts. I think I will start a separate repo for this :)

**Comment by swyxio** [comment]
https://github.com/sw-yx/awesome-dev-podcasts here you go! feel free to PR links and other suggestions

**Comment by lucidsif** [comment]
LOL, this is awesome. I guess you take the breadth-first approach to podcasts. Thank you for sharing!

Edit: You weren't kidding about 'a looot'.

**Comment by swyxio** [comment]
easy to subscribe, easy to delete :)
