### ISSUE TITLE
Name a few challenging aspects that you have encountered working in software development.

### ISSUE THREAD

**Issue by mattsre** [swyxio/ama#9]

**Comment by swyxio** [comment]
People, people, people.

- Most companies barely have any clue how to manage software engineers
- A company usually needs a unified codebase, but engineers can have very strong opinions about technical topics and can disagree extremely passionately. This can bring deadlock and/or employee churn.
- Most companies barely have any clue how to manage software products: You may be working a lot but working on the wrong thing. Even worse: it may be blindingly obvious to you that its wrong but it might not be your choice

theres a long list. but at the end of the day its mostly people related. Like most jobs :)
